### PR TITLE
Add ability to perform SOR request with DB data

### PR DESCRIPTION
**Pull request by timjrobinson**
- adds a new parameter useDb that makes SOR use DynamoDB for data instead of the graph, to test out E2E tests and make sure they work with DB data. 
- Fixes a bug where priceRates weren't being added to pools because all the data was coming from the subgraph. Now SOR pools are merged with Subgraph pools in the updatePools function. 
- Added tests to the above new things, added some new test factories for test data generation (mostly taken from the SDK). 
- Added a script to benchmark SOR with various minimum pool liquidity values. 

It also removes the /gnosis endpoint as it was doing exactly the same as /sor and it's not worth maintaining two endpoints. It was originally created so they would have a more stable version and we could experiment with /sor more but both ended up using the same code anyway and no one else is currently using the sor endpoint.

### CODE REVIEW

**Review by garethfuller — APPROVED** [review]
Should the test be failing?

**Comment by timjrobinson** [comment]
I added a script to benchmark DB speed vs Subgraph speed with various minimum liquidities of each pool. Here are the results. The first value is min liquidity, then it tests 4 different swaps with each level of minimum liquidity. 

```
subgraph-0 x 0.13 ops/sec ±149.92% (2 runs sampled)
subgraph-1 x 0.13 ops/sec ±37.10% (2 runs sampled)
subgraph-2 x 0.15 ops/sec ±9.87% (2 runs sampled)
subgraph-3 x 0.15 ops/sec ±56.90% (2 runs sampled)

0.001-0 x 1.21 ops/sec ±10.90% (5 runs sampled)
0.001-1 x 0.91 ops/sec ±4.80% (5 runs sampled)
0.001-2 x 1.69 ops/sec ±7.65% (5 runs sampled)
0.001-3 x 2.03 ops/sec ±19.08% (5 runs sampled)

0.01-0 x 1.36 ops/sec ±8.05% (5 runs sampled)
0.01-1 x 0.96 ops/sec ±6.63% (5 runs sampled)
0.01-2 x 1.76 ops/sec ±10.61% (5 runs sampled)
0.01-3 x 2.13 ops/sec ±10.66% (5 runs sampled)

0.1-0 x 1.38 ops/sec ±4.54% (5 runs sampled)
0.1-1 x 0.98 ops/sec ±6.93% (5 runs sampled)
0.1-2 x 1.81 ops/sec ±12.45% (5 runs sampled)
0.1-3 x 2.15 ops/sec ±17.69% (5 runs sampled)

1-0 x 1.45 ops/sec ±7.95% (5 runs sampled)
1-1 x 1.00 ops/sec ±3.50% (5 runs sampled)
1-2 x 1.84 ops/sec ±10.87% (5 runs sampled)
1-3 x 2.16 ops/sec ±16.14% (5 runs sampled)

10-0 x 2.09 ops/sec ±5.82% (5 runs sampled)
10-1 x 1.02 ops/sec ±5.13% (5 runs sampled)
10-2 x 1.77 ops/sec ±31.03% (5 runs sampled)
10-3 x 2.29 ops/sec ±17.10% (5 runs sampled)

100-0 x 2.33 ops/sec ±13.99% (5 runs sampled)
100-1 x 1.45 ops/sec ±7.61% (5 runs sampled)
100-2 x 2.65 ops/sec ±9.86% (5 runs sampled)
100-3 x 2.74 ops/sec ±10.67% (5 runs sampled)

1000-0 x 3.25 ops/sec ±4.91% (5 runs sampled)
1000-1 x 2.11 ops/sec ±14.50% (5 runs sampled)
1000-2 x 2.74 ops/sec ±18.17% (5 runs sampled)
1000-3 x 3.13 ops/sec ±14.32% (5 runs sampled)
```

**Comment by timjrobinson** [comment]
Spot Prices returned from each request (to ensure they're still returning good swaps with less pools):

```
api/subgraph-0: 0.14714497929310896022961248909224
api/subgraph-1: 1.000045894743015952
api/subgraph-2: 0.004251178638269719
api/subgraph-3: 0
api/0.001-0: 0.14714497929310896022961248909224
api/0.001-1: 1.000045894743015952
api/0.001-2: 0.004251178638269719
api/0.001-3: 0
api/0.01-0: 0.14714497929310896022961248909224
api/0.01-1: 1.000045894743015952
api/0.01-2: 0.004251178638269719
api/0.01-3: 0
api/0.1-0: 0.14714497929310896022961248909224
api/0.1-1: 1.000045894743015952
api/0.1-2: 0.004251178638269719
api/0.1-3: 0
api/1-0: 0.14714497929310896022961248909224
api/1-1: 1.000045894743015952
api/1-2: 0.004251178638269719
api/1-3: 0
api/10-0: 0.14714497929310896022961248909224
api/10-1: 1.000045894743015952
api/10-2: 0.004251178638269719
api/10-3: 0
api/100-0: 0.14714497929310896022961248909224
api/100-1: 1.000045894743015952
api/100-2: 0.004251178638269719
api/100-3: 0
api/1000-0: 0.14714497929310896022961248909224
api/1000-1: 1.000045894743015952
api/1000-2: 0.004251178638269719
api/1000-3: 0
```

**Comment by timjrobinson** [comment]
I put the results in a table so they're easier to parse:

```
Results
┌─────────┬────────────┬─────────────┬─────────────┬────────────────┬────────────────┐
│ (index) │ BAL -> DAI │ USDC -> DAI │ WETH -> BAL │ waUSDC -> WETH │ waUSDT -> USDC │
├─────────┼────────────┼─────────────┼─────────────┼────────────────┼────────────────┤
│ $0.001  │  '778ms'   │  '1196ms'   │   '491ms'   │    '763ms'     │    '1110ms'    │
│  $0.01  │  '702ms'   │  '1176ms'   │   '476ms'   │    '786ms'     │    '1098ms'    │
│  $0.1   │  '690ms'   │  '1185ms'   │   '476ms'   │    '769ms'     │    '1059ms'    │
│   $1    │  '671ms'   │  '1182ms'   │   '456ms'   │    '750ms'     │    '1079ms'    │
│   $10   │  '429ms'   │  '1091ms'   │   '378ms'   │    '668ms'     │    '1015ms'    │
│  $100   │  '370ms'   │   '705ms'   │   '339ms'   │    '576ms'     │    '669ms'     │
│  $1000  │  '289ms'   │   '461ms'   │   '276ms'   │    '375ms'     │    '433ms'     │
│ $10000  │  '239ms'   │   '393ms'   │   '248ms'   │    '315ms'     │    '374ms'     │
│ $100000 │  '211ms'   │   '368ms'   │   '234ms'   │    '316ms'     │    '353ms'     │
└─────────┴────────────┴─────────────┴─────────────┴────────────────┴────────────────┘

Spot prices
┌─────────┬───────────────────────────────────────┬────────────────────────┬────────────────────────┬──────────────────────┬────────────────────────┐
│ (index) │              BAL -> DAI               │      USDC -> DAI       │      WETH -> BAL       │    waUSDC -> WETH    │     waUSDT -> USDC     │
├─────────┼───────────────────────────────────────┼────────────────────────┼────────────────────────┼──────────────────────┼────────────────────────┤
│ $0.001  │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│  $0.01  │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│  $0.1   │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│   $1    │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│   $10   │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│  $100   │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│  $1000  │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│ $10000  │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
│ $100000 │ '0.146066850754720788672499896577464' │ '1.000064053143862455' │ '0.004282556853025654' │ '1641.3987887460783' │ '0.999943258739995442' │
└─────────┴───────────────────────────────────────┴────────────────────────┴────────────────────────┴──────────────────────┴────────────────────────┘
```

**Comment by timjrobinson** [comment]
Cowswap are changing their endpoint to `/sor` on Tuesday next week so this is blocked until then (as it removes the `/gnosis` endpoint)

**Pull request merged**
